"""empty message

Revision ID: 23a8e0df6cc1
Revises: 89c0acef49e8
Create Date: 2021-12-12 11:55:42.044105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a8e0df6cc1'
down_revision = '89c0acef49e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mahasiswa_dosen_satu_fkey', 'mahasiswa', type_='foreignkey')
    op.drop_constraint('mahasiswa_dosen_dua_fkey', 'mahasiswa', type_='foreignkey')
    op.create_foreign_key(None, 'mahasiswa', 'dosen', ['dosen_dua'], ['id'])
    op.create_foreign_key(None, 'mahasiswa', 'dosen', ['dosen_satu'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mahasiswa', type_='foreignkey')
    op.drop_constraint(None, 'mahasiswa', type_='foreignkey')
    op.create_foreign_key('mahasiswa_dosen_dua_fkey', 'mahasiswa', 'dosen', ['dosen_dua'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('mahasiswa_dosen_satu_fkey', 'mahasiswa', 'dosen', ['dosen_satu'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
